{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-robcompositions
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/robCompositions_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/robCompositions/robCompositions_{{ version }}.tar.gz
  sha256: 3532b61de7c474d075c7a88ab991be2ec02bbda15c52443577a15a4fcba0779e

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggally
    - r-mass
    - r-rcpp
    - r-vim
    - r-car
    - r-cluster
    - r-cvtools
    - r-data.table
    - r-e1071
    - r-fpc
    - r-ggplot2
    - r-kernlab
    - r-mclust
    - r-pls
    - r-robustbase
    - r-rrcov
    - r-sroc
    - r-tidyr
    - r-zcompositions
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-ggally
    - r-mass
    - r-rcpp
    - r-vim
    - r-car
    - r-cluster
    - r-cvtools
    - r-data.table
    - r-e1071
    - r-fpc
    - r-ggplot2
    - r-kernlab
    - r-mclust
    - r-pls
    - r-robustbase
    - r-rrcov
    - r-sroc
    - r-tidyr
    - r-zcompositions

test:
  commands:
    - $R -e "library('robCompositions')"           # [not win]
    - "\"%R%\" -e \"library('robCompositions')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=robCompositions
  license: GPL (>= 2)
  summary: Methods for analysis of compositional data including robust methods, imputation, methods
    to replace rounded zeros, (robust) outlier detection for compositional data, (robust)
    principal component analysis for compositional data, (robust) factor analysis for
    compositional data, (robust) discriminant analysis for compositional data (Fisher
    rule), robust regression with compositional predictors and (robust) Anderson-Darling
    normality tests for compositional data as well as popular log-ratio transformations
    (addLR, cenLR, isomLR, and their inverse transformations). In addition, visualisation
    and diagnostic tools are implemented as well as high and low-level plot functions
    for the ternary diagram.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: robCompositions
# Type: Package
# Title: Compositional Data Analysis
# Version: 2.1.0
# Date: 2019-04-15
# Depends: R (>= 3.0.0), robustbase, ggplot2, data.table, e1071, pls
# LinkingTo: Rcpp
# Imports: car, cvTools, rrcov, cluster, fpc, GGally, kernlab, MASS, mclust, Rcpp, sROC, tidyr, VIM, zCompositions
# Suggests: knitr
# VignetteBuilder: knitr
# Authors@R: c( person("Matthias", "Templ", email="matthias.templ@gmail.com", role=c("aut", "cre")), person("Karel", "Hron", email="Alexander.Kowarik@statistik.gv.at", role="aut"), person("Peter", "Filzmoser", email = "Bernhard.Meindl@statistik.gv.at", role="aut"), person("Kamila", "Facevicova", email="kamila.facevicova@gmail.com", role="ctb"), person("Petra", "Kynclova", email="kynclova.petra@gmail.com", role="ctb"), person("Jan", "Walach", email ="walach.jan@gmail.com ", role="ctb"), person("Veronika", "Pintar", email ="vroni.pintar@gmx.at", role="ctb"), person("Jiajia", "Chen", email ="chenjiajia0401@163.com", role="ctb"),	 person("Dominika", "Miksova", email ="miksovadominika1@gmail.com", role="ctb"))
# Maintainer: Matthias Templ <matthias.templ@gmail.com>
# Description: Methods for analysis of compositional data including robust methods, imputation, methods to replace rounded zeros, (robust) outlier detection for compositional data, (robust) principal component analysis for compositional data, (robust) factor analysis for compositional data, (robust) discriminant analysis for compositional data (Fisher rule), robust regression with compositional predictors and (robust) Anderson-Darling normality tests for compositional data as well as popular log-ratio transformations (addLR, cenLR, isomLR, and their inverse transformations). In addition, visualisation and diagnostic tools are implemented as well as high and low-level plot functions for the ternary diagram.
# License: GPL (>= 2)
# LazyLoad: yes
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-04-15 16:33:54 UTC; teml
# Author: Matthias Templ [aut, cre], Karel Hron [aut], Peter Filzmoser [aut], Kamila Facevicova [ctb], Petra Kynclova [ctb], Jan Walach [ctb], Veronika Pintar [ctb], Jiajia Chen [ctb], Dominika Miksova [ctb]
# Repository: CRAN
# Date/Publication: 2019-04-15 17:22:43 UTC
