appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: IuVsbHj1FsYrLASog5XXJjKSQN+maHl4Hxdx7Aqktyec8EtlqLhJCWxES1zNsfREDD+Y2MVX407m4SJqbSD9dIVIAfssFcfTATIwfJPYf66u+qq/Ne7u2+9Mj92Tjt0DR2R7ktWN4u3M8N3DTtnxpxKeopJZ2RT4CxSs3oTG5s4yWr5QN+fzMJGiiyL7WCqWkxLR3IiuHwCneh4mjbrQXEKxPNkrtHdmCEULNS4w4SZ27yi1H4F/Rt1NPRjd9VlvHvvJ4z+JiBlUis4KwpvunIWTTevH5jm6rK4eYnNId5qXEyay+AUB2pQE4fu9YUP7j6UzfNtX+XBt6AOXQshjJJ0g/0mQbUT3xuIAg8PcTBc2e4S9j/yhrRKVXdwHCEE7Sy/pPTJZEYTuKuhJzzqEsKyXpTiGQFAyWnvM2UEP6KMmTMis0IJrHST01TcfEOYbDPa8n8AEIrfDofcZVz9JPwJ1XW0AdaWe1rDbnBmwVcT26Xpy1Sk/AoC/5hcTcFjnpDW0WmQtMmzNGtBktKsxmtroiPRrNFdFIfV9HCg/oQn1sxv/vjLzoxnWXjpKvSegokTdublaIHm66VIvexwdq+wH/D4xsv4wUjzMnXtioZ1VIpD3k7XSTQEh264vLXqlv/C64Ek9XVdSjyRQRzXF7bdpPr/Culzvo5J4BzYO8PE=
conda_forge_output_validation: false
